# Dependencies
markdown:         redcarpet
plugins: [jekyll-paginate]
# Permalinks
permalink:        /:categories/:title


# Setup
title:            Christopher<br>Calascione
tagline:          'A Portfolio Site'
description:      ''
baseurl:          /
collections:
- projects


# Base theme author
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         3

# Custom vars
version:          2.1.0

github: https://www.github.com/calascionec

exclude:
  - package.json
  - node_modules
  - gulpfile.js
